### ISSUE TITLE
刘大神，从上线就在关注了，最近也没啥动静

### ISSUE THREAD

**Issue by ancientry** [hero-node/hero-js#3]
刘大神，您好，我是菜鸟一枚，从上线就在关注了，但是最近好像没啥动静了，模版组件看了一下就几个，有点少，而且入门摸索时间有点长，其实可以参考其他HBulider一样，弄一个集成的开发工具

**Comment by ancientry** [comment]
希望HERO越来越好

**Comment by gpliu** [comment]
使用hero-mobile/hero-cli 一步一步开始啊
